spring.application.name=smartbudget

spring.datasource.url=jdbc:postgresql://localhost:65433/smartbudget
spring.datasource.username=admin
spring.datasource.password=admin

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database=postgresql
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml

server.error.include-message=always
server.error.include-exception=false
